from OpenGL.GLUT import *
from OpenGL.GLU import *
from OpenGL.GL import *
import sys
from Cube import Cube

matrix = [
                      
                       [(-1.1,+1.1,+1.1), 'rw'],[(+0.0,+1.1,+1.1), 'rw'],[(+1.1,+1.1,+1.1), 'rw'],     #(0,0,0),(0,0,1),(0,0,2)
                       [(-1.1,+0.0,+1.1), 'rw'],[(+0.0,+0.0,+1.1), 'rw'],[(+1.1,+0.0,+1.1), 'rw'],     #(0,1,0),(0,1,1),(0,1,2)
                       [(-1.1,-1.1,+1.1), 'rw'],[(+0.0,-1.1,+1.1), 'rw'],[(+1.1,-1.1,+1.1), 'rw'],     #(0,2,0),(0,2,1),(0,2,2)
                      
                       [(-1.1,+1.1,+0.0), 'rw'],[(+0.0,+1.1,+0.0), 'rw'],[(+1.1,+1.1,+0.0), 'rw'],     #(1,0,0),(1,0,1),(1,0,2)
                       [(-1.1,+0.0,+0.0), 'rw'],[(+0.0,+0.0,+0.0), 'rw'],[(+1.1,+0.0,+0.0), 'rw'],     #(1,1,0),(1,1,1),(1,1,2)
                       [(-1.1,-1.1,+0.0), 'rw'],[(+0.0,-1.1,+0.0), 'rw'],[(+1.1,-1.1,+0.0), 'rw'],     #(1,2,0),(1,2,1),(1,2,2)
                      
                       [(-1.1,+1.1,-1.1), 'rw'],[(+0.0,+1.1,-1.1), 'rw'],[(+1.1,+1.1,-1.1), 'rw'],     #(2,0,0),(2,0,1),(2,0,2)
                       [(-1.1,+0.0,-1.1), 'rw'],[(+0.0,+0.0,-1.1), 'rw'],[(+1.1,+0.0,-1.1), 'rw'],     #(2,1,0),(2,1,1),(2,1,2)
                       [(-1.1,-1.1,-1.1), 'rw'],[(+0.0,-1.1,-1.1), 'rw'],[(+1.1,-1.1,-1.1), 'rw']      #(2,2,0),(2,2,1),(2,2,2)
                                                                          
             ]

def rc():
    global matrix

    	
    for vect, config in matrix:
        c = Cube(vect, 1, config)
        faces = c.faces
        vertices = c.vertex
        glBegin(GL_QUADS)
	
        for face, color in faces:
            glColor3fv(color)
            for vertex in face:
                glVertex3fv(vertices[vertex])
        glEnd()

def keyPressed(*args):
  global matrix
  if args[0] == 'o':
    if matrix[6][1] == 'rw': matrix[6][1] = 'rb'#<-------
    elif matrix[6][1] == 'rb': matrix[6][1] = 'ry'
    elif matrix[6][1] == 'ry': matrix[6][1] = 'rg'
    elif matrix[6][1] == 'rg': matrix[6][1] = 'rw'
    elif matrix[6][1] == 'ow': matrix[6][1] = 'og' #<-------
    elif matrix[6][1] == 'og': matrix[6][1] = 'oy'
    elif matrix[6][1] == 'oy': matrix[6][1] = 'ob'
    elif matrix[6][1] == 'ob': matrix[6][1] = 'ow'
    elif matrix[6][1] == 'bw': matrix[6][1] = 'bo'#<-------
    elif matrix[6][1] == 'bo': matrix[6][1] = 'by'
    elif matrix[6][1] == 'by': matrix[6][1] = 'br'
    elif matrix[6][1] == 'br': matrix[6][1] = 'bw'
    elif matrix[6][1] == 'gw': matrix[6][1] = 'gr'#<-------
    elif matrix[6][1] == 'gr': matrix[6][1] = 'gy'
    elif matrix[6][1] == 'gy': matrix[6][1] = 'go'
    elif matrix[6][1] == 'go': matrix[6][1] = 'gw'
    elif matrix[6][1] == 'wr': matrix[6][1] = 'wg'#<-------
    elif matrix[6][1] == 'wg': matrix[6][1] = 'wo'
    elif matrix[6][1] == 'wo': matrix[6][1] = 'wb'
    elif matrix[6][1] == 'wb': matrix[6][1] = 'wr'
    elif matrix[6][1] == 'yr': matrix[6][1] = 'yb'#<-------
    elif matrix[6][1] == 'yb': matrix[6][1] = 'yo'
    elif matrix[6][1] == 'yo': matrix[6][1] = 'yg'
    elif matrix[6][1] == 'yg': matrix[6][1] = 'yr'

    if matrix[24][1] == 'rw': matrix[24][1] = 'rb'
    elif matrix[24][1] == 'rb': matrix[24][1] = 'ry'
    elif matrix[24][1] == 'ry': matrix[24][1] = 'rg'
    elif matrix[24][1] == 'rg': matrix[24][1] = 'rw'
    elif matrix[24][1] == 'ow': matrix[24][1] = 'og'#<-------
    elif matrix[24][1] == 'og': matrix[24][1] = 'oy'
    elif matrix[24][1] == 'oy': matrix[24][1] = 'ob'
    elif matrix[24][1] == 'ob': matrix[24][1] = 'ow'
    elif matrix[24][1] == 'bw': matrix[24][1] = 'bo'
    elif matrix[24][1] == 'bo': matrix[24][1] = 'by'
    elif matrix[24][1] == 'by': matrix[24][1] = 'br'
    elif matrix[24][1] == 'br': matrix[24][1] = 'bw'
    elif matrix[24][1] == 'gw': matrix[24][1] = 'gr'
    elif matrix[24][1] == 'gr': matrix[24][1] = 'gy'
    elif matrix[24][1] == 'gy': matrix[24][1] = 'go'
    elif matrix[24][1] == 'go': matrix[24][1] = 'gw'
    elif matrix[24][1] == 'wr': matrix[24][1] = 'wg'
    elif matrix[24][1] == 'wg': matrix[24][1] = 'wo'
    elif matrix[24][1] == 'wo': matrix[24][1] = 'wb'
    elif matrix[24][1] == 'wb': matrix[24][1] = 'wr'
    elif matrix[24][1] == 'yr': matrix[24][1] = 'yb'
    elif matrix[24][1] == 'yb': matrix[24][1] = 'yo'
    elif matrix[24][1] == 'yo': matrix[24][1] = 'yg'
    elif matrix[24][1] == 'yg': matrix[24][1] = 'yr'

    if matrix[26][1] == 'rw': matrix[26][1] = 'rb'
    elif matrix[26][1] == 'rb': matrix[26][1] = 'ry'
    elif matrix[26][1] == 'ry': matrix[26][1] = 'rg'
    elif matrix[26][1] == 'rg': matrix[26][1] = 'rw'
    elif matrix[26][1] == 'ow': matrix[26][1] = 'og'#<-------
    elif matrix[26][1] == 'og': matrix[26][1] = 'oy'
    elif matrix[26][1] == 'oy': matrix[26][1] = 'ob'
    elif matrix[26][1] == 'ob': matrix[26][1] = 'ob'
    elif matrix[26][1] == 'bw': matrix[26][1] = 'bo'
    elif matrix[26][1] == 'bo': matrix[26][1] = 'by'
    elif matrix[26][1] == 'by': matrix[26][1] = 'br'
    elif matrix[26][1] == 'br': matrix[26][1] = 'bw'
    elif matrix[26][1] == 'gw': matrix[26][1] = 'gr'
    elif matrix[26][1] == 'gr': matrix[26][1] = 'gy'
    elif matrix[26][1] == 'gy': matrix[26][1] = 'go'
    elif matrix[26][1] == 'go': matrix[26][1] = 'gw'
    elif matrix[26][1] == 'wr': matrix[26][1] = 'wg'
    elif matrix[26][1] == 'wg': matrix[26][1] = 'wo'
    elif matrix[26][1] == 'wo': matrix[26][1] = 'wb'
    elif matrix[26][1] == 'wb': matrix[26][1] = 'wr'
    elif matrix[26][1] == 'yr': matrix[26][1] = 'yb'
    elif matrix[26][1] == 'yb': matrix[26][1] = 'yo'
    elif matrix[26][1] == 'yo': matrix[26][1] = 'yg'
    elif matrix[26][1] == 'yg': matrix[26][1] = 'yr'

    if matrix[8][1] == 'rw': matrix[8][1] = 'rb'
    elif matrix[8][1] == 'rb': matrix[8][1] = 'ry'
    elif matrix[8][1] == 'ry': matrix[8][1] = 'rg'
    elif matrix[8][1] == 'rg': matrix[8][1] = 'rw'
    elif matrix[8][1] == 'ow': matrix[8][1] = 'og'#<-------
    elif matrix[8][1] == 'og': matrix[8][1] = 'oy'
    elif matrix[8][1] == 'oy': matrix[8][1] = 'ob'
    elif matrix[8][1] == 'ob': matrix[8][1] = 'ow'
    elif matrix[8][1] == 'bw': matrix[8][1] = 'bo'
    elif matrix[8][1] == 'bo': matrix[8][1] = 'by'
    elif matrix[8][1] == 'by': matrix[8][1] = 'br'
    elif matrix[8][1] == 'br': matrix[8][1] = 'bw'
    elif matrix[8][1] == 'gw': matrix[8][1] = 'gr'
    elif matrix[8][1] == 'gr': matrix[8][1] = 'gy'
    elif matrix[8][1] == 'gy': matrix[8][1] = 'go'
    elif matrix[8][1] == 'go': matrix[8][1] = 'gw'
    elif matrix[8][1] == 'wr': matrix[8][1] = 'wg'
    elif matrix[8][1] == 'wg': matrix[8][1] = 'wo'
    elif matrix[8][1] == 'wo': matrix[8][1] = 'wb'
    elif matrix[8][1] == 'wb': matrix[8][1] = 'wr'
    elif matrix[8][1] == 'yr': matrix[8][1] = 'yb'
    elif matrix[8][1] == 'yb': matrix[8][1] = 'yo'
    elif matrix[8][1] == 'yo': matrix[8][1] = 'yg'
    elif matrix[8][1] == 'yg': matrix[8][1] = 'yr'

    if matrix[15][1] == 'rw': matrix[15][1] = 'rb'
    elif matrix[15][1] == 'rb': matrix[15][1] = 'ry'
    elif matrix[15][1] == 'ry': matrix[15][1] = 'rg'
    elif matrix[15][1] == 'rg': matrix[15][1] = 'rw'
    elif matrix[15][1] == 'ow': matrix[15][1] = 'og'#<-------
    elif matrix[15][1] == 'og': matrix[15][1] = 'oy'
    elif matrix[15][1] == 'oy': matrix[15][1] = 'ob'
    elif matrix[15][1] == 'ob': matrix[15][1] = 'ow'
    elif matrix[15][1] == 'bw': matrix[15][1] = 'bo'
    elif matrix[15][1] == 'bo': matrix[15][1] = 'by'
    elif matrix[15][1] == 'by': matrix[15][1] = 'br'
    elif matrix[15][1] == 'br': matrix[15][1] = 'bw'
    elif matrix[15][1] == 'gw': matrix[15][1] = 'gr'
    elif matrix[15][1] == 'gr': matrix[15][1] = 'gy'
    elif matrix[15][1] == 'gy': matrix[15][1] = 'go'
    elif matrix[15][1] == 'go': matrix[15][1] = 'gw'
    elif matrix[15][1] == 'wr': matrix[15][1] = 'wg'
    elif matrix[15][1] == 'wg': matrix[15][1] = 'wo'
    elif matrix[15][1] == 'wo': matrix[15][1] = 'wb'
    elif matrix[15][1] == 'wb': matrix[15][1] = 'wr'
    elif matrix[15][1] == 'yr': matrix[15][1] = 'yb'
    elif matrix[15][1] == 'yb': matrix[15][1] = 'yo'
    elif matrix[15][1] == 'yo': matrix[15][1] = 'yg'
    elif matrix[15][1] == 'yg': matrix[15][1] = 'yr'

    if matrix[25][1] == 'rw': matrix[25][1] = 'rb'
    elif matrix[25][1] == 'rb': matrix[25][1] = 'ry'
    elif matrix[25][1] == 'ry': matrix[25][1] = 'rg'
    elif matrix[25][1] == 'rg': matrix[25][1] = 'rw'
    elif matrix[25][1] == 'ow': matrix[25][1] = 'og'#<-------
    elif matrix[25][1] == 'og': matrix[25][1] = 'oy'
    elif matrix[25][1] == 'oy': matrix[25][1] = 'ob'
    elif matrix[25][1] == 'ob': matrix[25][1] = 'ow'
    elif matrix[25][1] == 'bw': matrix[25][1] = 'bo'
    elif matrix[25][1] == 'bo': matrix[25][1] = 'by'
    elif matrix[25][1] == 'by': matrix[25][1] = 'br'
    elif matrix[25][1] == 'br': matrix[25][1] = 'bw'
    elif matrix[25][1] == 'gw': matrix[25][1] = 'gr'
    elif matrix[25][1] == 'gr': matrix[25][1] = 'gy'
    elif matrix[25][1] == 'gy': matrix[25][1] = 'go'
    elif matrix[25][1] == 'go': matrix[25][1] = 'gw'
    elif matrix[25][1] == 'wr': matrix[25][1] = 'wg'
    elif matrix[25][1] == 'wg': matrix[25][1] = 'wo'
    elif matrix[25][1] == 'wo': matrix[25][1] = 'wb'
    elif matrix[25][1] == 'wb': matrix[25][1] = 'wr'
    elif matrix[25][1] == 'yr': matrix[25][1] = 'yb'
    elif matrix[25][1] == 'yb': matrix[25][1] = 'yo'
    elif matrix[25][1] == 'yo': matrix[25][1] = 'yg'
    elif matrix[25][1] == 'yg': matrix[25][1] = 'yr'

    if matrix[17][1] == 'rw': matrix[17][1] = 'rb'
    elif matrix[17][1] == 'rb': matrix[17][1] = 'ry'
    elif matrix[17][1] == 'ry': matrix[17][1] = 'rg'
    elif matrix[17][1] == 'rg': matrix[17][1] = 'rw'
    elif matrix[17][1] == 'ow': matrix[17][1] = 'og'#<-------
    elif matrix[17][1] == 'og': matrix[17][1] = 'oy'
    elif matrix[17][1] == 'oy': matrix[17][1] = 'ob'
    elif matrix[17][1] == 'ob': matrix[17][1] = 'ow'
    elif matrix[17][1] == 'bw': matrix[17][1] = 'bo'
    elif matrix[17][1] == 'bo': matrix[17][1] = 'by'
    elif matrix[17][1] == 'by': matrix[17][1] = 'br'
    elif matrix[17][1] == 'br': matrix[17][1] = 'bw'
    elif matrix[17][1] == 'gw': matrix[17][1] = 'gr'
    elif matrix[17][1] == 'gr': matrix[17][1] = 'gy'
    elif matrix[17][1] == 'gy': matrix[17][1] = 'go'
    elif matrix[17][1] == 'go': matrix[17][1] = 'gw'
    elif matrix[17][1] == 'wr': matrix[17][1] = 'wg'
    elif matrix[17][1] == 'wg': matrix[17][1] = 'wo'
    elif matrix[17][1] == 'wo': matrix[17][1] = 'wb'
    elif matrix[17][1] == 'wb': matrix[17][1] = 'wr'
    elif matrix[17][1] == 'yr': matrix[17][1] = 'yb'
    elif matrix[17][1] == 'yb': matrix[17][1] = 'yo'
    elif matrix[17][1] == 'yo': matrix[17][1] = 'yg'
    elif matrix[17][1] == 'yg': matrix[17][1] = 'yr'

    if matrix[7][1] == 'rw': matrix[7][1] = 'rb'
    elif matrix[7][1] == 'rb': matrix[7][1] = 'ry'
    elif matrix[7][1] == 'ry': matrix[7][1] = 'rg'
    elif matrix[7][1] == 'rg': matrix[7][1] = 'rw'
    elif matrix[7][1] == 'ow': matrix[7][1] = 'og'#<-------
    elif matrix[7][1] == 'og': matrix[7][1] = 'oy'
    elif matrix[7][1] == 'oy': matrix[7][1] = 'ob'
    elif matrix[7][1] == 'ob': matrix[7][1] = 'ow'
    elif matrix[7][1] == 'bw': matrix[7][1] = 'bo'
    elif matrix[7][1] == 'bo': matrix[7][1] = 'by'
    elif matrix[7][1] == 'by': matrix[7][1] = 'br'
    elif matrix[7][1] == 'br': matrix[7][1] = 'bw'
    elif matrix[7][1] == 'gw': matrix[7][1] = 'gr'
    elif matrix[7][1] == 'gr': matrix[7][1] = 'gy'
    elif matrix[7][1] == 'gy': matrix[7][1] = 'go'
    elif matrix[7][1] == 'go': matrix[7][1] = 'gw'
    elif matrix[7][1] == 'wr': matrix[7][1] = 'wg'
    elif matrix[7][1] == 'wg': matrix[7][1] = 'wo'
    elif matrix[7][1] == 'wo': matrix[7][1] = 'wb'
    elif matrix[7][1] == 'wb': matrix[7][1] = 'wr'
    elif matrix[7][1] == 'yr': matrix[7][1] = 'yb'
    elif matrix[7][1] == 'yb': matrix[7][1] = 'yo'
    elif matrix[7][1] == 'yo': matrix[7][1] = 'yg'
    elif matrix[7][1] == 'yg': matrix[7][1] = 'yr'


    matrix[6][1], matrix[24][1], matrix[26][1], matrix[8][1] = matrix[8][1], matrix[6][1], matrix[24][1], matrix[26][1]
    matrix[15][1], matrix[25][1], matrix[17][1], matrix[7][1] = matrix[7][1], matrix[15][1], matrix[25][1], matrix[17][1]

  if args[0] == 'r':
    if matrix[0][1] == 'rw': matrix[0][1] = 'rb'#<-------
    elif matrix[0][1] == 'rb': matrix[0][1] = 'ry'
    elif matrix[0][1] == 'ry': matrix[0][1] = 'rg'
    elif matrix[0][1] == 'rg': matrix[0][1] = 'rw'
    elif matrix[0][1] == 'ow': matrix[0][1] = 'og' #<-------
    elif matrix[0][1] == 'og': matrix[0][1] = 'oy'
    elif matrix[0][1] == 'oy': matrix[0][1] = 'ob'
    elif matrix[0][1] == 'ob': matrix[0][1] = 'ow'
    elif matrix[0][1] == 'bw': matrix[0][1] = 'bo'#<-------
    elif matrix[0][1] == 'bo': matrix[0][1] = 'by'
    elif matrix[0][1] == 'by': matrix[0][1] = 'br'
    elif matrix[0][1] == 'br': matrix[0][1] = 'bw'
    elif matrix[0][1] == 'gw': matrix[0][1] = 'gr'#<-------
    elif matrix[0][1] == 'gr': matrix[0][1] = 'gy'
    elif matrix[0][1] == 'gy': matrix[0][1] = 'go'
    elif matrix[0][1] == 'go': matrix[0][1] = 'gw'
    elif matrix[0][1] == 'wr': matrix[0][1] = 'wg'#<-------
    elif matrix[0][1] == 'wg': matrix[0][1] = 'wo'
    elif matrix[0][1] == 'wo': matrix[0][1] = 'wb'
    elif matrix[0][1] == 'wb': matrix[0][1] = 'wr'
    elif matrix[0][1] == 'yr': matrix[0][1] = 'yb'#<-------
    elif matrix[0][1] == 'yb': matrix[0][1] = 'yo'
    elif matrix[0][1] == 'yo': matrix[0][1] = 'yg'
    elif matrix[0][1] == 'yg': matrix[0][1] = 'yr'

    if matrix[18][1] == 'rw': matrix[18][1] = 'rb'
    elif matrix[18][1] == 'rb': matrix[18][1] = 'ry'
    elif matrix[18][1] == 'ry': matrix[18][1] = 'rg'
    elif matrix[18][1] == 'rg': matrix[18][1] = 'rw'
    elif matrix[18][1] == 'ow': matrix[18][1] = 'og'#<-------
    elif matrix[18][1] == 'og': matrix[18][1] = 'oy'
    elif matrix[18][1] == 'oy': matrix[18][1] = 'ob'
    elif matrix[18][1] == 'ob': matrix[18][1] = 'ow'
    elif matrix[18][1] == 'bw': matrix[18][1] = 'bo'
    elif matrix[18][1] == 'bo': matrix[18][1] = 'by'
    elif matrix[18][1] == 'by': matrix[18][1] = 'br'
    elif matrix[18][1] == 'br': matrix[18][1] = 'bw'
    elif matrix[18][1] == 'gw': matrix[18][1] = 'gr'
    elif matrix[18][1] == 'gr': matrix[18][1] = 'gy'
    elif matrix[18][1] == 'gy': matrix[18][1] = 'go'
    elif matrix[18][1] == 'go': matrix[18][1] = 'gw'
    elif matrix[18][1] == 'wr': matrix[18][1] = 'wg'
    elif matrix[18][1] == 'wg': matrix[18][1] = 'wo'
    elif matrix[18][1] == 'wo': matrix[18][1] = 'wb'
    elif matrix[18][1] == 'wb': matrix[18][1] = 'wr'
    elif matrix[18][1] == 'yr': matrix[18][1] = 'yb'
    elif matrix[18][1] == 'yb': matrix[18][1] = 'yo'
    elif matrix[18][1] == 'yo': matrix[18][1] = 'yg'
    elif matrix[18][1] == 'yg': matrix[18][1] = 'yr'

    if matrix[20][1] == 'rw': matrix[20][1] = 'rb'
    elif matrix[20][1] == 'rb': matrix[20][1] = 'ry'
    elif matrix[20][1] == 'ry': matrix[20][1] = 'rg'
    elif matrix[20][1] == 'rg': matrix[20][1] = 'rw'
    elif matrix[20][1] == 'ow': matrix[20][1] = 'og'#<-------
    elif matrix[20][1] == 'og': matrix[20][1] = 'oy'
    elif matrix[20][1] == 'oy': matrix[20][1] = 'ob'
    elif matrix[20][1] == 'ob': matrix[20][1] = 'ob'
    elif matrix[20][1] == 'bw': matrix[20][1] = 'bo'
    elif matrix[20][1] == 'bo': matrix[20][1] = 'by'
    elif matrix[20][1] == 'by': matrix[20][1] = 'br'
    elif matrix[20][1] == 'br': matrix[20][1] = 'bw'
    elif matrix[20][1] == 'gw': matrix[20][1] = 'gr'
    elif matrix[20][1] == 'gr': matrix[20][1] = 'gy'
    elif matrix[20][1] == 'gy': matrix[20][1] = 'go'
    elif matrix[20][1] == 'go': matrix[20][1] = 'gw'
    elif matrix[20][1] == 'wr': matrix[20][1] = 'wg'
    elif matrix[20][1] == 'wg': matrix[20][1] = 'wo'
    elif matrix[20][1] == 'wo': matrix[20][1] = 'wb'
    elif matrix[20][1] == 'wb': matrix[20][1] = 'wr'
    elif matrix[20][1] == 'yr': matrix[20][1] = 'yb'
    elif matrix[20][1] == 'yb': matrix[20][1] = 'yo'
    elif matrix[20][1] == 'yo': matrix[20][1] = 'yg'
    elif matrix[20][1] == 'yg': matrix[20][1] = 'yr'

    if matrix[2][1] == 'rw': matrix[2][1] = 'rb'
    elif matrix[2][1] == 'rb': matrix[2][1] = 'ry'
    elif matrix[2][1] == 'ry': matrix[2][1] = 'rg'
    elif matrix[2][1] == 'rg': matrix[2][1] = 'rw'
    elif matrix[2][1] == 'ow': matrix[2][1] = 'og'#<-------
    elif matrix[2][1] == 'og': matrix[2][1] = 'oy'
    elif matrix[2][1] == 'oy': matrix[2][1] = 'ob'
    elif matrix[2][1] == 'ob': matrix[2][1] = 'ow'
    elif matrix[2][1] == 'bw': matrix[2][1] = 'bo'
    elif matrix[2][1] == 'bo': matrix[2][1] = 'by'
    elif matrix[2][1] == 'by': matrix[2][1] = 'br'
    elif matrix[2][1] == 'br': matrix[2][1] = 'bw'
    elif matrix[2][1] == 'gw': matrix[2][1] = 'gr'
    elif matrix[2][1] == 'gr': matrix[2][1] = 'gy'
    elif matrix[2][1] == 'gy': matrix[2][1] = 'go'
    elif matrix[2][1] == 'go': matrix[2][1] = 'gw'
    elif matrix[2][1] == 'wr': matrix[2][1] = 'wg'
    elif matrix[2][1] == 'wg': matrix[2][1] = 'wo'
    elif matrix[2][1] == 'wo': matrix[2][1] = 'wb'
    elif matrix[2][1] == 'wb': matrix[2][1] = 'wr'
    elif matrix[2][1] == 'yr': matrix[2][1] = 'yb'
    elif matrix[2][1] == 'yb': matrix[2][1] = 'yo'
    elif matrix[2][1] == 'yo': matrix[2][1] = 'yg'
    elif matrix[2][1] == 'yg': matrix[2][1] = 'yr'

    if matrix[1][1] == 'rw': matrix[1][1] = 'rb'
    elif matrix[1][1] == 'rb': matrix[1][1] = 'ry'
    elif matrix[1][1] == 'ry': matrix[1][1] = 'rg'
    elif matrix[1][1] == 'rg': matrix[1][1] = 'rw'
    elif matrix[1][1] == 'ow': matrix[1][1] = 'og'#<-------
    elif matrix[1][1] == 'og': matrix[1][1] = 'oy'
    elif matrix[1][1] == 'oy': matrix[1][1] = 'ob'
    elif matrix[1][1] == 'ob': matrix[1][1] = 'ow'
    elif matrix[1][1] == 'bw': matrix[1][1] = 'bo'
    elif matrix[1][1] == 'bo': matrix[1][1] = 'by'
    elif matrix[1][1] == 'by': matrix[1][1] = 'br'
    elif matrix[1][1] == 'br': matrix[1][1] = 'bw'
    elif matrix[1][1] == 'gw': matrix[1][1] = 'gr'
    elif matrix[1][1] == 'gr': matrix[1][1] = 'gy'
    elif matrix[1][1] == 'gy': matrix[1][1] = 'go'
    elif matrix[1][1] == 'go': matrix[1][1] = 'gw'
    elif matrix[1][1] == 'wr': matrix[1][1] = 'wg'
    elif matrix[1][1] == 'wg': matrix[1][1] = 'wo'
    elif matrix[1][1] == 'wo': matrix[1][1] = 'wb'
    elif matrix[1][1] == 'wb': matrix[1][1] = 'wr'
    elif matrix[1][1] == 'yr': matrix[1][1] = 'yb'
    elif matrix[1][1] == 'yb': matrix[1][1] = 'yo'
    elif matrix[1][1] == 'yo': matrix[1][1] = 'yg'
    elif matrix[1][1] == 'yg': matrix[1][1] = 'yr'

    if matrix[9][1] == 'rw': matrix[9][1] = 'rb'
    elif matrix[9][1] == 'rb': matrix[9][1] = 'ry'
    elif matrix[9][1] == 'ry': matrix[9][1] = 'rg'
    elif matrix[9][1] == 'rg': matrix[9][1] = 'rw'
    elif matrix[9][1] == 'ow': matrix[9][1] = 'og'#<-------
    elif matrix[9][1] == 'og': matrix[9][1] = 'oy'
    elif matrix[9][1] == 'oy': matrix[9][1] = 'ob'
    elif matrix[9][1] == 'ob': matrix[9][1] = 'ow'
    elif matrix[9][1] == 'bw': matrix[9][1] = 'bo'
    elif matrix[9][1] == 'bo': matrix[9][1] = 'by'
    elif matrix[9][1] == 'by': matrix[9][1] = 'br'
    elif matrix[9][1] == 'br': matrix[9][1] = 'bw'
    elif matrix[9][1] == 'gw': matrix[9][1] = 'gr'
    elif matrix[9][1] == 'gr': matrix[9][1] = 'gy'
    elif matrix[9][1] == 'gy': matrix[9][1] = 'go'
    elif matrix[9][1] == 'go': matrix[9][1] = 'gw'
    elif matrix[9][1] == 'wr': matrix[9][1] = 'wg'
    elif matrix[9][1] == 'wg': matrix[9][1] = 'wo'
    elif matrix[9][1] == 'wo': matrix[9][1] = 'wb'
    elif matrix[9][1] == 'wb': matrix[9][1] = 'wr'
    elif matrix[9][1] == 'yr': matrix[9][1] = 'yb'
    elif matrix[9][1] == 'yb': matrix[9][1] = 'yo'
    elif matrix[9][1] == 'yo': matrix[9][1] = 'yg'
    elif matrix[9][1] == 'yg': matrix[9][1] = 'yr'

    if matrix[19][1] == 'rw': matrix[19][1] = 'rb'
    elif matrix[19][1] == 'rb': matrix[19][1] = 'ry'
    elif matrix[19][1] == 'ry': matrix[19][1] = 'rg'
    elif matrix[19][1] == 'rg': matrix[19][1] = 'rw'
    elif matrix[19][1] == 'ow': matrix[19][1] = 'og'#<-------
    elif matrix[19][1] == 'og': matrix[19][1] = 'oy'
    elif matrix[19][1] == 'oy': matrix[19][1] = 'ob'
    elif matrix[19][1] == 'ob': matrix[19][1] = 'ow'
    elif matrix[19][1] == 'bw': matrix[19][1] = 'bo'
    elif matrix[19][1] == 'bo': matrix[19][1] = 'by'
    elif matrix[19][1] == 'by': matrix[19][1] = 'br'
    elif matrix[19][1] == 'br': matrix[19][1] = 'bw'
    elif matrix[19][1] == 'gw': matrix[19][1] = 'gr'
    elif matrix[19][1] == 'gr': matrix[19][1] = 'gy'
    elif matrix[19][1] == 'gy': matrix[19][1] = 'go'
    elif matrix[19][1] == 'go': matrix[19][1] = 'gw'
    elif matrix[19][1] == 'wr': matrix[19][1] = 'wg'
    elif matrix[19][1] == 'wg': matrix[19][1] = 'wo'
    elif matrix[19][1] == 'wo': matrix[19][1] = 'wb'
    elif matrix[19][1] == 'wb': matrix[19][1] = 'wr'
    elif matrix[19][1] == 'yr': matrix[19][1] = 'yb'
    elif matrix[19][1] == 'yb': matrix[19][1] = 'yo'
    elif matrix[19][1] == 'yo': matrix[19][1] = 'yg'
    elif matrix[19][1] == 'yg': matrix[19][1] = 'yr'

    if matrix[11][1] == 'rw': matrix[11][1] = 'rb'
    elif matrix[11][1] == 'rb': matrix[11][1] = 'ry'
    elif matrix[11][1] == 'ry': matrix[11][1] = 'rg'
    elif matrix[11][1] == 'rg': matrix[11][1] = 'rw'
    elif matrix[11][1] == 'ow': matrix[11][1] = 'og'#<-------
    elif matrix[11][1] == 'og': matrix[11][1] = 'oy'
    elif matrix[11][1] == 'oy': matrix[11][1] = 'ob'
    elif matrix[11][1] == 'ob': matrix[11][1] = 'ow'
    elif matrix[11][1] == 'bw': matrix[11][1] = 'bo'
    elif matrix[11][1] == 'bo': matrix[11][1] = 'by'
    elif matrix[11][1] == 'by': matrix[11][1] = 'br'
    elif matrix[11][1] == 'br': matrix[11][1] = 'bw'
    elif matrix[11][1] == 'gw': matrix[11][1] = 'gr'
    elif matrix[11][1] == 'gr': matrix[11][1] = 'gy'
    elif matrix[11][1] == 'gy': matrix[11][1] = 'go'
    elif matrix[11][1] == 'go': matrix[11][1] = 'gw'
    elif matrix[11][1] == 'wr': matrix[11][1] = 'wg'
    elif matrix[11][1] == 'wg': matrix[11][1] = 'wo'
    elif matrix[11][1] == 'wo': matrix[11][1] = 'wb'
    elif matrix[11][1] == 'wb': matrix[11][1] = 'wr'
    elif matrix[11][1] == 'yr': matrix[11][1] = 'yb'
    elif matrix[11][1] == 'yb': matrix[11][1] = 'yo'
    elif matrix[11][1] == 'yo': matrix[11][1] = 'yg'
    elif matrix[11][1] == 'yg': matrix[11][1] = 'yr'


    matrix[0][1], matrix[18][1], matrix[20][1], matrix[2][1] = matrix[2][1], matrix[0][1], matrix[18][1], matrix[20][1]
    matrix[1][1], matrix[9][1], matrix[19][1], matrix[11][1] = matrix[11][1], matrix[1][1], matrix[9][1], matrix[19][1]

  if args[0] == 'b':
    if matrix[20][1] == 'rw': matrix[20][1] = 'wo'
    elif matrix[20][1] == 'wo': matrix[20][1] = 'oy'
    elif matrix[20][1] == 'oy': matrix[20][1] = 'yr'
    elif matrix[20][1] == 'yr': matrix[20][1] = 'rw'
    elif matrix[20][1] == 'rg': matrix[20][1] = 'go'
    elif matrix[20][1] == 'go': matrix[20][1] = 'ob'
    elif matrix[20][1] == 'ob': matrix[20][1] = 'br'
    elif matrix[20][1] == 'br': matrix[20][1] = 'rg'
    elif matrix[20][1] == 'ry': matrix[20][1] = 'yo'
    elif matrix[20][1] == 'yo': matrix[20][1] = 'ow'
    elif matrix[20][1] == 'ow': matrix[20][1] = 'wr'
    elif matrix[20][1] == 'wr': matrix[20][1] = 'ry'
    elif matrix[20][1] == 'rb': matrix[20][1] = 'bo'
    elif matrix[20][1] == 'bo': matrix[20][1] = 'og'
    elif matrix[20][1] == 'og': matrix[20][1] = 'gr'
    elif matrix[20][1] == 'gr': matrix[20][1] = 'rb'
    elif matrix[20][1] == 'bw': matrix[20][1] = 'wg'
    elif matrix[20][1] == 'wg': matrix[20][1] = 'gy'
    elif matrix[20][1] == 'gy': matrix[20][1] = 'yb'
    elif matrix[20][1] == 'yb': matrix[20][1] = 'bw'
    elif matrix[20][1] == 'by': matrix[20][1] = 'yg'
    elif matrix[20][1] == 'yg': matrix[20][1] = 'gw'
    elif matrix[20][1] == 'gw': matrix[20][1] = 'wb'
    elif matrix[20][1] == 'wb': matrix[20][1] = 'by'

    if matrix[26][1] == 'rw': matrix[26][1] = 'wo'
    elif matrix[26][1] == 'wo': matrix[26][1] = 'oy'
    elif matrix[26][1] == 'oy': matrix[26][1] = 'yr'
    elif matrix[26][1] == 'yr': matrix[26][1] = 'rw'
    elif matrix[26][1] == 'rg': matrix[26][1] = 'go'
    elif matrix[26][1] == 'go': matrix[26][1] = 'ob'
    elif matrix[26][1] == 'ob': matrix[26][1] = 'br'
    elif matrix[26][1] == 'br': matrix[26][1] = 'rg'
    elif matrix[26][1] == 'ry': matrix[26][1] = 'yo'
    elif matrix[26][1] == 'yo': matrix[26][1] = 'ow'
    elif matrix[26][1] == 'ow': matrix[26][1] = 'wr'
    elif matrix[26][1] == 'wr': matrix[26][1] = 'ry'
    elif matrix[26][1] == 'rb': matrix[26][1] = 'bo'
    elif matrix[26][1] == 'bo': matrix[26][1] = 'og'
    elif matrix[26][1] == 'og': matrix[26][1] = 'gr'
    elif matrix[26][1] == 'gr': matrix[26][1] = 'rb'
    elif matrix[26][1] == 'bw': matrix[26][1] = 'wg'
    elif matrix[26][1] == 'wg': matrix[26][1] = 'gy'
    elif matrix[26][1] == 'gy': matrix[26][1] = 'yb'
    elif matrix[26][1] == 'yb': matrix[26][1] = 'bw'
    elif matrix[26][1] == 'by': matrix[26][1] = 'yg'
    elif matrix[26][1] == 'yg': matrix[26][1] = 'gw'
    elif matrix[26][1] == 'gw': matrix[26][1] = 'wb'
    elif matrix[26][1] == 'wb': matrix[26][1] = 'by'

    if matrix[8][1] == 'rw': matrix[8][1] = 'wo'
    elif matrix[8][1] == 'wo': matrix[8][1] = 'oy'
    elif matrix[8][1] == 'oy': matrix[8][1] = 'yr'
    elif matrix[8][1] == 'yr': matrix[8][1] = 'rw'
    elif matrix[8][1] == 'rg': matrix[8][1] = 'go'
    elif matrix[8][1] == 'go': matrix[8][1] = 'ob'
    elif matrix[8][1] == 'ob': matrix[8][1] = 'br'
    elif matrix[8][1] == 'br': matrix[8][1] = 'rg'
    elif matrix[8][1] == 'ry': matrix[8][1] = 'yo'
    elif matrix[8][1] == 'yo': matrix[8][1] = 'ow'
    elif matrix[8][1] == 'ow': matrix[8][1] = 'wr'
    elif matrix[8][1] == 'wr': matrix[8][1] = 'ry'
    elif matrix[8][1] == 'rb': matrix[8][1] = 'bo'
    elif matrix[8][1] == 'bo': matrix[8][1] = 'og'
    elif matrix[8][1] == 'og': matrix[8][1] = 'gr'
    elif matrix[8][1] == 'gr': matrix[8][1] = 'rb'
    elif matrix[8][1] == 'bw': matrix[8][1] = 'wg'
    elif matrix[8][1] == 'wg': matrix[8][1] = 'gy'
    elif matrix[8][1] == 'gy': matrix[8][1] = 'yb'
    elif matrix[8][1] == 'yb': matrix[8][1] = 'bw'
    elif matrix[8][1] == 'by': matrix[8][1] = 'yg'
    elif matrix[8][1] == 'yg': matrix[8][1] = 'gw'
    elif matrix[8][1] == 'gw': matrix[8][1] = 'wb'
    elif matrix[8][1] == 'wb': matrix[8][1] = 'by'

    if matrix[2][1] == 'rw': matrix[2][1] = 'wo'
    elif matrix[2][1] == 'wo': matrix[2][1] = 'oy'
    elif matrix[2][1] == 'oy': matrix[2][1] = 'yr'
    elif matrix[2][1] == 'yr': matrix[2][1] = 'rw'
    elif matrix[2][1] == 'rg': matrix[2][1] = 'go' 
    elif matrix[2][1] == 'go': matrix[2][1] = 'ob'
    elif matrix[2][1] == 'ob': matrix[2][1] = 'br' 
    elif matrix[2][1] == 'br': matrix[2][1] = 'rg' 
    elif matrix[2][1] == 'ry': matrix[2][1] = 'yo'
    elif matrix[2][1] == 'yo': matrix[2][1] = 'ow'
    elif matrix[2][1] == 'ow': matrix[2][1] = 'wr'
    elif matrix[2][1] == 'wr': matrix[2][1] = 'ry'
    elif matrix[2][1] == 'rb': matrix[2][1] = 'bo'
    elif matrix[2][1] == 'bo': matrix[2][1] = 'og'
    elif matrix[2][1] == 'og': matrix[2][1] = 'gr'
    elif matrix[2][1] == 'gr': matrix[2][1] = 'rb'
    elif matrix[2][1] == 'bw': matrix[2][1] = 'wg'
    elif matrix[2][1] == 'wg': matrix[2][1] = 'gy'
    elif matrix[2][1] == 'gy': matrix[2][1] = 'yb'
    elif matrix[2][1] == 'yb': matrix[2][1] = 'bw'
    elif matrix[2][1] == 'by': matrix[2][1] = 'yg'
    elif matrix[2][1] == 'yg': matrix[2][1] = 'gw'
    elif matrix[2][1] == 'gw': matrix[2][1] = 'wb'
    elif matrix[2][1] == 'wb': matrix[2][1] = 'by'

    if matrix[11][1] == 'rw': matrix[11][1] = 'wo'
    elif matrix[11][1] == 'wo': matrix[11][1] = 'oy'
    elif matrix[11][1] == 'oy': matrix[11][1] = 'yr'
    elif matrix[11][1] == 'yr': matrix[11][1] = 'rw'
    elif matrix[11][1] == 'rg': matrix[11][1] = 'go'
    elif matrix[11][1] == 'go': matrix[11][1] = 'ob'
    elif matrix[11][1] == 'ob': matrix[11][1] = 'br'
    elif matrix[11][1] == 'br': matrix[11][1] = 'rg'
    elif matrix[11][1] == 'ry': matrix[11][1] = 'yo'
    elif matrix[11][1] == 'yo': matrix[11][1] = 'ow'
    elif matrix[11][1] == 'ow': matrix[11][1] = 'wr'
    elif matrix[11][1] == 'wr': matrix[11][1] = 'ry'
    elif matrix[11][1] == 'rb': matrix[11][1] = 'bo'
    elif matrix[11][1] == 'bo': matrix[11][1] = 'og'
    elif matrix[11][1] == 'og': matrix[11][1] = 'gr'
    elif matrix[11][1] == 'gr': matrix[11][1] = 'rb'
    elif matrix[11][1] == 'bw': matrix[11][1] = 'wg'
    elif matrix[11][1] == 'wg': matrix[11][1] = 'gy'
    elif matrix[11][1] == 'gy': matrix[11][1] = 'yb'
    elif matrix[11][1] == 'yb': matrix[11][1] = 'bw'
    elif matrix[11][1] == 'by': matrix[11][1] = 'yg'
    elif matrix[11][1] == 'yg': matrix[11][1] = 'gw'
    elif matrix[11][1] == 'gw': matrix[11][1] = 'wb'
    elif matrix[11][1] == 'wb': matrix[11][1] = 'by'

    if matrix[23][1] == 'rw': matrix[23][1] = 'wo'
    elif matrix[23][1] == 'wo': matrix[23][1] = 'oy'
    elif matrix[23][1] == 'oy': matrix[23][1] = 'yr'
    elif matrix[23][1] == 'yr': matrix[23][1] = 'rw'
    elif matrix[23][1] == 'rg': matrix[23][1] = 'go'
    elif matrix[23][1] == 'go': matrix[23][1] = 'ob'
    elif matrix[23][1] == 'ob': matrix[23][1] = 'br'
    elif matrix[23][1] == 'br': matrix[23][1] = 'rg'
    elif matrix[23][1] == 'ry': matrix[23][1] = 'yo'
    elif matrix[23][1] == 'yo': matrix[23][1] = 'ow'
    elif matrix[23][1] == 'ow': matrix[23][1] = 'wr'
    elif matrix[23][1] == 'wr': matrix[23][1] = 'ry'
    elif matrix[23][1] == 'rb': matrix[23][1] = 'bo'
    elif matrix[23][1] == 'bo': matrix[23][1] = 'og'
    elif matrix[23][1] == 'og': matrix[23][1] = 'gr'
    elif matrix[23][1] == 'gr': matrix[23][1] = 'rb'
    elif matrix[23][1] == 'bw': matrix[23][1] = 'wg'
    elif matrix[23][1] == 'wg': matrix[23][1] = 'gy'
    elif matrix[23][1] == 'gy': matrix[23][1] = 'yb'
    elif matrix[23][1] == 'yb': matrix[23][1] = 'bw'
    elif matrix[23][1] == 'by': matrix[23][1] = 'yg'
    elif matrix[23][1] == 'yg': matrix[23][1] = 'gw'
    elif matrix[23][1] == 'gw': matrix[23][1] = 'wb'
    elif matrix[23][1] == 'wb': matrix[23][1] = 'by'

    if matrix[17][1] == 'rw': matrix[17][1] = 'wo'
    elif matrix[17][1] == 'wo': matrix[17][1] = 'oy'
    elif matrix[17][1] == 'oy': matrix[17][1] = 'yr'
    elif matrix[17][1] == 'yr': matrix[17][1] = 'rw'
    elif matrix[17][1] == 'rg': matrix[17][1] = 'go'
    elif matrix[17][1] == 'go': matrix[17][1] = 'ob'
    elif matrix[17][1] == 'ob': matrix[17][1] = 'br'
    elif matrix[17][1] == 'br': matrix[17][1] = 'rg'
    elif matrix[17][1] == 'ry': matrix[17][1] = 'yo'
    elif matrix[17][1] == 'yo': matrix[17][1] = 'ow'
    elif matrix[17][1] == 'ow': matrix[17][1] = 'wr'
    elif matrix[17][1] == 'wr': matrix[17][1] = 'ry'
    elif matrix[17][1] == 'rb': matrix[17][1] = 'bo'
    elif matrix[17][1] == 'bo': matrix[17][1] = 'og'
    elif matrix[17][1] == 'og': matrix[17][1] = 'gr'
    elif matrix[17][1] == 'gr': matrix[17][1] = 'rb'
    elif matrix[17][1] == 'bw': matrix[17][1] = 'wg'
    elif matrix[17][1] == 'wg': matrix[17][1] = 'gy'
    elif matrix[17][1] == 'gy': matrix[17][1] = 'yb'
    elif matrix[17][1] == 'yb': matrix[17][1] = 'bw'
    elif matrix[17][1] == 'by': matrix[17][1] = 'yg'
    elif matrix[17][1] == 'yg': matrix[17][1] = 'gw'
    elif matrix[17][1] == 'gw': matrix[17][1] = 'wb'
    elif matrix[17][1] == 'wb': matrix[17][1] = 'by'

    if matrix[5][1] == 'rw': matrix[5][1] = 'wo'
    elif matrix[5][1] == 'wo': matrix[5][1] = 'oy'
    elif matrix[5][1] == 'oy': matrix[5][1] = 'yr'
    elif matrix[5][1] == 'yr': matrix[5][1] = 'rw'
    elif matrix[5][1] == 'rg': matrix[5][1] = 'go'
    elif matrix[5][1] == 'go': matrix[5][1] = 'ob'
    elif matrix[5][1] == 'ob': matrix[5][1] = 'br'
    elif matrix[5][1] == 'br': matrix[5][1] = 'rg'
    elif matrix[5][1] == 'ry': matrix[5][1] = 'yo'
    elif matrix[5][1] == 'yo': matrix[5][1] = 'ow'
    elif matrix[5][1] == 'ow': matrix[5][1] = 'wr'
    elif matrix[5][1] == 'wr': matrix[5][1] = 'ry'
    elif matrix[5][1] == 'rb': matrix[5][1] = 'bo'
    elif matrix[5][1] == 'bo': matrix[5][1] = 'og'
    elif matrix[5][1] == 'og': matrix[5][1] = 'gr'
    elif matrix[5][1] == 'gr': matrix[5][1] = 'rb'
    elif matrix[5][1] == 'bw': matrix[5][1] = 'wg'
    elif matrix[5][1] == 'wg': matrix[5][1] = 'gy'
    elif matrix[5][1] == 'gy': matrix[5][1] = 'yb'
    elif matrix[5][1] == 'yb': matrix[5][1] = 'bw'
    elif matrix[5][1] == 'by': matrix[5][1] = 'yg'
    elif matrix[5][1] == 'yg': matrix[5][1] = 'gw'
    elif matrix[5][1] == 'gw': matrix[5][1] = 'wb'
    elif matrix[5][1] == 'wb': matrix[5][1] = 'by'

    matrix[20][1], matrix[26][1], matrix[8][1], matrix[2][1] = matrix[2][1], matrix[20][1], matrix[26][1], matrix[8][1]
    matrix[11][1], matrix[23][1], matrix[17][1], matrix[5][1] = matrix[5][1], matrix[11][1], matrix[23][1], matrix[17][1]

  if args[0] == 'w':
    if matrix[0][1] == 'rw': matrix[0][1] = 'bw'
    elif matrix[0][1] == 'bw': matrix[0][1] = 'ow'
    elif matrix[0][1] == 'ow': matrix[0][1] = 'gw'
    elif matrix[0][1] == 'gw': matrix[0][1] = 'rw'
    elif matrix[0][1] == 'rb': matrix[0][1] = 'yb'
    elif matrix[0][1] == 'yb': matrix[0][1] = 'ob'
    elif matrix[0][1] == 'ob': matrix[0][1] = 'wb'
    elif matrix[0][1] == 'wb': matrix[0][1] = 'rb'
    elif matrix[0][1] == 'ry': matrix[0][1] = 'gy'
    elif matrix[0][1] == 'gy': matrix[0][1] = 'oy'
    elif matrix[0][1] == 'oy': matrix[0][1] = 'by'
    elif matrix[0][1] == 'by': matrix[0][1] = 'ry'
    elif matrix[0][1] == 'rg': matrix[0][1] = 'wg'
    elif matrix[0][1] == 'wg': matrix[0][1] = 'og'
    elif matrix[0][1] == 'og': matrix[0][1] = 'yg'
    elif matrix[0][1] == 'yg': matrix[0][1] = 'rg'
    elif matrix[0][1] == 'wr': matrix[0][1] = 'gr'
    elif matrix[0][1] == 'gr': matrix[0][1] = 'yr'
    elif matrix[0][1] == 'yr': matrix[0][1] = 'br'
    elif matrix[0][1] == 'br': matrix[0][1] = 'wr'
    elif matrix[0][1] == 'wo': matrix[0][1] = 'bo'
    elif matrix[0][1] == 'bo': matrix[0][1] = 'yo'
    elif matrix[0][1] == 'yo': matrix[0][1] = 'go'
    elif matrix[0][1] == 'go': matrix[0][1] = 'wo'

    if matrix[6][1] == 'rw': matrix[6][1] = 'bw'
    elif matrix[6][1] == 'bw': matrix[6][1] = 'ow' 
    elif matrix[6][1] == 'ow': matrix[6][1] = 'gw'
    elif matrix[6][1] == 'gw': matrix[6][1] = 'rw'
    elif matrix[6][1] == 'rb': matrix[6][1] = 'yb'
    elif matrix[6][1] == 'yb': matrix[6][1] = 'ob'
    elif matrix[6][1] == 'ob': matrix[6][1] = 'wb'
    elif matrix[6][1] == 'wb': matrix[6][1] = 'rb'
    elif matrix[6][1] == 'ry': matrix[6][1] = 'gy'
    elif matrix[6][1] == 'gy': matrix[6][1] = 'oy'
    elif matrix[6][1] == 'oy': matrix[6][1] = 'by'
    elif matrix[6][1] == 'by': matrix[6][1] = 'ry'
    elif matrix[6][1] == 'rg': matrix[6][1] = 'wg'
    elif matrix[6][1] == 'wg': matrix[6][1] = 'og'
    elif matrix[6][1] == 'og': matrix[6][1] = 'yg'
    elif matrix[6][1] == 'yg': matrix[6][1] = 'rg'
    elif matrix[6][1] == 'wr': matrix[6][1] = 'gr'
    elif matrix[6][1] == 'gr': matrix[6][1] = 'yr'
    elif matrix[6][1] == 'yr': matrix[6][1] = 'br'
    elif matrix[6][1] == 'br': matrix[6][1] = 'wr'
    elif matrix[6][1] == 'wo': matrix[6][1] = 'bo'
    elif matrix[6][1] == 'bo': matrix[6][1] = 'yo'
    elif matrix[6][1] == 'yo': matrix[6][1] = 'go'
    elif matrix[6][1] == 'go': matrix[6][1] = 'wo'

    if matrix[8][1] == 'rw': matrix[8][1] = 'bw'
    elif matrix[8][1] == 'bw': matrix[8][1] = 'ow' 
    elif matrix[8][1] == 'ow': matrix[8][1] = 'gw'
    elif matrix[8][1] == 'gw': matrix[8][1] = 'rw'
    elif matrix[8][1] == 'rb': matrix[8][1] = 'yb'
    elif matrix[8][1] == 'yb': matrix[8][1] = 'ob'
    elif matrix[8][1] == 'ob': matrix[8][1] = 'wb'
    elif matrix[8][1] == 'wb': matrix[8][1] = 'rb'
    elif matrix[8][1] == 'ry': matrix[8][1] = 'gy'
    elif matrix[8][1] == 'gy': matrix[8][1] = 'oy'
    elif matrix[8][1] == 'oy': matrix[8][1] = 'by'
    elif matrix[8][1] == 'by': matrix[8][1] = 'ry'
    elif matrix[8][1] == 'rg': matrix[8][1] = 'wg'
    elif matrix[8][1] == 'wg': matrix[8][1] = 'og'
    elif matrix[8][1] == 'og': matrix[8][1] = 'yg'
    elif matrix[8][1] == 'yg': matrix[8][1] = 'rg'
    elif matrix[8][1] == 'wr': matrix[8][1] = 'gr'
    elif matrix[8][1] == 'gr': matrix[8][1] = 'yr'
    elif matrix[8][1] == 'yr': matrix[8][1] = 'br'
    elif matrix[8][1] == 'br': matrix[8][1] = 'wr'
    elif matrix[8][1] == 'wo': matrix[8][1] = 'bo'
    elif matrix[8][1] == 'bo': matrix[8][1] = 'yo'
    elif matrix[8][1] == 'yo': matrix[8][1] = 'go'
    elif matrix[8][1] == 'go': matrix[8][1] = 'wo'

    if matrix[2][1] == 'rw': matrix[2][1] = 'bw'
    elif matrix[2][1] == 'bw': matrix[2][1] = 'ow'
    elif matrix[2][1] == 'ow': matrix[2][1] = 'gw'
    elif matrix[2][1] == 'gw': matrix[2][1] = 'rw'
    elif matrix[2][1] == 'rb': matrix[2][1] = 'yb'
    elif matrix[2][1] == 'yb': matrix[2][1] = 'ob'
    elif matrix[2][1] == 'ob': matrix[2][1] = 'wb'
    elif matrix[2][1] == 'wb': matrix[2][1] = 'rb'
    elif matrix[2][1] == 'ry': matrix[2][1] = 'gy'
    elif matrix[2][1] == 'gy': matrix[2][1] = 'oy'
    elif matrix[2][1] == 'oy': matrix[2][1] = 'by'
    elif matrix[2][1] == 'by': matrix[2][1] = 'ry'
    elif matrix[2][1] == 'rg': matrix[2][1] = 'wg'
    elif matrix[2][1] == 'wg': matrix[2][1] = 'og'
    elif matrix[2][1] == 'og': matrix[2][1] = 'yg'
    elif matrix[2][1] == 'yg': matrix[2][1] = 'rg'
    elif matrix[2][1] == 'wr': matrix[2][1] = 'gr'
    elif matrix[2][1] == 'gr': matrix[2][1] = 'yr'
    elif matrix[2][1] == 'yr': matrix[2][1] = 'br'
    elif matrix[2][1] == 'br': matrix[2][1] = 'wr'
    elif matrix[2][1] == 'wo': matrix[2][1] = 'bo'
    elif matrix[2][1] == 'bo': matrix[2][1] = 'yo'
    elif matrix[2][1] == 'yo': matrix[2][1] = 'go'
    elif matrix[2][1] == 'go': matrix[2][1] = 'wo'

    if matrix[3][1] == 'rw': matrix[3][1] = 'bw'
    elif matrix[3][1] == 'bw': matrix[3][1] = 'ow' 
    elif matrix[3][1] == 'ow': matrix[3][1] = 'gw'
    elif matrix[3][1] == 'gw': matrix[3][1] = 'rw'
    elif matrix[3][1] == 'rb': matrix[3][1] = 'yb'
    elif matrix[3][1] == 'yb': matrix[3][1] = 'ob'
    elif matrix[3][1] == 'ob': matrix[3][1] = 'wb'
    elif matrix[3][1] == 'wb': matrix[3][1] = 'rb'
    elif matrix[3][1] == 'ry': matrix[3][1] = 'gy'
    elif matrix[3][1] == 'gy': matrix[3][1] = 'oy'
    elif matrix[3][1] == 'oy': matrix[3][1] = 'by'
    elif matrix[3][1] == 'by': matrix[3][1] = 'ry'
    elif matrix[3][1] == 'rg': matrix[3][1] = 'wg'
    elif matrix[3][1] == 'wg': matrix[3][1] = 'og'
    elif matrix[3][1] == 'og': matrix[3][1] = 'yg'
    elif matrix[3][1] == 'yg': matrix[3][1] = 'rg'
    elif matrix[3][1] == 'wr': matrix[3][1] = 'gr'
    elif matrix[3][1] == 'gr': matrix[3][1] = 'yr'
    elif matrix[3][1] == 'yr': matrix[3][1] = 'br'
    elif matrix[3][1] == 'br': matrix[3][1] = 'wr'
    elif matrix[3][1] == 'wo': matrix[3][1] = 'bo'
    elif matrix[3][1] == 'bo': matrix[3][1] = 'yo'
    elif matrix[3][1] == 'yo': matrix[3][1] = 'go'
    elif matrix[3][1] == 'go': matrix[3][1] = 'wo'

    if matrix[7][1] == 'rw': matrix[7][1] = 'bw'
    elif matrix[7][1] == 'bw': matrix[7][1] = 'ow'
    elif matrix[7][1] == 'ow': matrix[7][1] = 'gw'
    elif matrix[7][1] == 'gw': matrix[7][1] = 'rw'
    elif matrix[7][1] == 'rb': matrix[7][1] = 'yb'
    elif matrix[7][1] == 'yb': matrix[7][1] = 'ob'
    elif matrix[7][1] == 'ob': matrix[7][1] = 'wb'
    elif matrix[7][1] == 'wb': matrix[7][1] = 'rb'
    elif matrix[7][1] == 'ry': matrix[7][1] = 'gy'
    elif matrix[7][1] == 'gy': matrix[7][1] = 'oy'
    elif matrix[7][1] == 'oy': matrix[7][1] = 'by'
    elif matrix[7][1] == 'by': matrix[7][1] = 'ry'
    elif matrix[7][1] == 'rg': matrix[7][1] = 'wg'
    elif matrix[7][1] == 'wg': matrix[7][1] = 'og'
    elif matrix[7][1] == 'og': matrix[7][1] = 'yg'
    elif matrix[7][1] == 'yg': matrix[7][1] = 'rg'
    elif matrix[7][1] == 'wr': matrix[7][1] = 'gr'
    elif matrix[7][1] == 'gr': matrix[7][1] = 'yr'
    elif matrix[7][1] == 'yr': matrix[7][1] = 'br'
    elif matrix[7][1] == 'br': matrix[7][1] = 'wr'
    elif matrix[7][1] == 'wo': matrix[7][1] = 'bo'
    elif matrix[7][1] == 'bo': matrix[7][1] = 'yo'
    elif matrix[7][1] == 'yo': matrix[7][1] = 'go'
    elif matrix[7][1] == 'go': matrix[7][1] = 'wo'

    if matrix[5][1] == 'rw': matrix[5][1] = 'bw'
    elif matrix[5][1] == 'bw': matrix[5][1] = 'ow'
    elif matrix[5][1] == 'ow': matrix[5][1] = 'gw'
    elif matrix[5][1] == 'gw': matrix[5][1] = 'rw'
    elif matrix[5][1] == 'rb': matrix[5][1] = 'yb'
    elif matrix[5][1] == 'yb': matrix[5][1] = 'ob'
    elif matrix[5][1] == 'ob': matrix[5][1] = 'wb'
    elif matrix[5][1] == 'wb': matrix[5][1] = 'rb'
    elif matrix[5][1] == 'ry': matrix[5][1] = 'gy'
    elif matrix[5][1] == 'gy': matrix[5][1] = 'oy'
    elif matrix[5][1] == 'oy': matrix[5][1] = 'by'
    elif matrix[5][1] == 'by': matrix[5][1] = 'ry'
    elif matrix[5][1] == 'rg': matrix[5][1] = 'wg'
    elif matrix[5][1] == 'wg': matrix[5][1] = 'og'
    elif matrix[5][1] == 'og': matrix[5][1] = 'yg'
    elif matrix[5][1] == 'yg': matrix[5][1] = 'rg'
    elif matrix[5][1] == 'wr': matrix[5][1] = 'gr'
    elif matrix[5][1] == 'gr': matrix[5][1] = 'yr'
    elif matrix[5][1] == 'yr': matrix[5][1] = 'br'
    elif matrix[5][1] == 'br': matrix[5][1] = 'wr'
    elif matrix[5][1] == 'wo': matrix[5][1] = 'bo'
    elif matrix[5][1] == 'bo': matrix[5][1] = 'yo'
    elif matrix[5][1] == 'yo': matrix[5][1] = 'go'
    elif matrix[5][1] == 'go': matrix[5][1] = 'wo'

    if matrix[1][1] == 'rw': matrix[1][1] = 'bw'
    elif matrix[1][1] == 'bw': matrix[1][1] = 'ow'
    elif matrix[1][1] == 'ow': matrix[1][1] = 'gw'
    elif matrix[1][1] == 'gw': matrix[1][1] = 'rw'
    elif matrix[1][1] == 'rb': matrix[1][1] = 'yb'
    elif matrix[1][1] == 'yb': matrix[1][1] = 'ob'
    elif matrix[1][1] == 'ob': matrix[1][1] = 'wb'
    elif matrix[1][1] == 'wb': matrix[1][1] = 'rb'
    elif matrix[1][1] == 'ry': matrix[1][1] = 'gy'
    elif matrix[1][1] == 'gy': matrix[1][1] = 'oy'
    elif matrix[1][1] == 'oy': matrix[1][1] = 'by'
    elif matrix[1][1] == 'by': matrix[1][1] = 'ry'
    elif matrix[1][1] == 'rg': matrix[1][1] = 'wg'
    elif matrix[1][1] == 'wg': matrix[1][1] = 'og'
    elif matrix[1][1] == 'og': matrix[1][1] = 'yg'
    elif matrix[1][1] == 'yg': matrix[1][1] = 'rg'
    elif matrix[1][1] == 'wr': matrix[1][1] = 'gr'
    elif matrix[1][1] == 'gr': matrix[1][1] = 'yr'
    elif matrix[1][1] == 'yr': matrix[1][1] = 'br'
    elif matrix[1][1] == 'br': matrix[1][1] = 'wr'
    elif matrix[1][1] == 'wo': matrix[1][1] = 'bo'
    elif matrix[1][1] == 'bo': matrix[1][1] = 'yo'
    elif matrix[1][1] == 'yo': matrix[1][1] = 'go'
    elif matrix[1][1] == 'go': matrix[1][1] = 'wo'

    matrix[0][1], matrix[6][1], matrix[8][1], matrix[2][1] = matrix[2][1], matrix[0][1], matrix[6][1], matrix[8][1]
    matrix[3][1], matrix[7][1], matrix[5][1], matrix[1][1] = matrix[1][1], matrix[3][1], matrix[7][1], matrix[5][1]
  
  if args[0] == 'g':
    if matrix[18][1] == 'rw': matrix[18][1] = 'wo'
    elif matrix[18][1] == 'wo': matrix[18][1] = 'oy'
    elif matrix[18][1] == 'oy': matrix[18][1] = 'yr'
    elif matrix[18][1] == 'yr': matrix[18][1] = 'rw'
    elif matrix[18][1] == 'rg': matrix[18][1] = 'go'
    elif matrix[18][1] == 'go': matrix[18][1] = 'ob'
    elif matrix[18][1] == 'ob': matrix[18][1] = 'br'
    elif matrix[18][1] == 'br': matrix[18][1] = 'rg'
    elif matrix[18][1] == 'ry': matrix[18][1] = 'yo'
    elif matrix[18][1] == 'yo': matrix[18][1] = 'ow'
    elif matrix[18][1] == 'ow': matrix[18][1] = 'wr'
    elif matrix[18][1] == 'wr': matrix[18][1] = 'ry'
    elif matrix[18][1] == 'rb': matrix[18][1] = 'bo'
    elif matrix[18][1] == 'bo': matrix[18][1] = 'og'
    elif matrix[18][1] == 'og': matrix[18][1] = 'gr'
    elif matrix[18][1] == 'gr': matrix[18][1] = 'rb'
    elif matrix[18][1] == 'bw': matrix[18][1] = 'wg'
    elif matrix[18][1] == 'wg': matrix[18][1] = 'gy'
    elif matrix[18][1] == 'gy': matrix[18][1] = 'yb'
    elif matrix[18][1] == 'yb': matrix[18][1] = 'bw'
    elif matrix[18][1] == 'by': matrix[18][1] = 'yg'
    elif matrix[18][1] == 'yg': matrix[18][1] = 'gw'
    elif matrix[18][1] == 'gw': matrix[18][1] = 'wb'
    elif matrix[18][1] == 'wb': matrix[18][1] = 'by'

    if matrix[24][1] == 'rw': matrix[24][1] = 'wo'
    elif matrix[24][1] == 'wo': matrix[24][1] = 'oy'
    elif matrix[24][1] == 'oy': matrix[24][1] = 'yr'
    elif matrix[24][1] == 'yr': matrix[24][1] = 'rw'
    elif matrix[24][1] == 'rg': matrix[24][1] = 'go'
    elif matrix[24][1] == 'go': matrix[24][1] = 'ob'
    elif matrix[24][1] == 'ob': matrix[24][1] = 'br'
    elif matrix[24][1] == 'br': matrix[24][1] = 'rg'
    elif matrix[24][1] == 'ry': matrix[24][1] = 'yo'
    elif matrix[24][1] == 'yo': matrix[24][1] = 'ow'
    elif matrix[24][1] == 'ow': matrix[24][1] = 'wr'
    elif matrix[24][1] == 'wr': matrix[24][1] = 'ry'
    elif matrix[24][1] == 'rb': matrix[24][1] = 'bo'
    elif matrix[24][1] == 'bo': matrix[24][1] = 'og'
    elif matrix[24][1] == 'og': matrix[24][1] = 'gr'
    elif matrix[24][1] == 'gr': matrix[24][1] = 'rb'
    elif matrix[24][1] == 'bw': matrix[24][1] = 'wg'
    elif matrix[24][1] == 'wg': matrix[24][1] = 'gy'
    elif matrix[24][1] == 'gy': matrix[24][1] = 'yb'
    elif matrix[24][1] == 'yb': matrix[24][1] = 'bw'
    elif matrix[24][1] == 'by': matrix[24][1] = 'yg'
    elif matrix[24][1] == 'yg': matrix[24][1] = 'gw'
    elif matrix[24][1] == 'gw': matrix[24][1] = 'wb'
    elif matrix[24][1] == 'wb': matrix[24][1] = 'by'

    if matrix[6][1] == 'rw': matrix[6][1] = 'wo'
    elif matrix[6][1] == 'wo': matrix[6][1] = 'oy'
    elif matrix[6][1] == 'oy': matrix[6][1] = 'yr'
    elif matrix[6][1] == 'yr': matrix[6][1] = 'rw'
    elif matrix[6][1] == 'rg': matrix[6][1] = 'go'
    elif matrix[6][1] == 'go': matrix[6][1] = 'ob'
    elif matrix[6][1] == 'ob': matrix[6][1] = 'br'
    elif matrix[6][1] == 'br': matrix[6][1] = 'rg'
    elif matrix[6][1] == 'ry': matrix[6][1] = 'yo'
    elif matrix[6][1] == 'yo': matrix[6][1] = 'ow'
    elif matrix[6][1] == 'ow': matrix[6][1] = 'wr'
    elif matrix[6][1] == 'wr': matrix[6][1] = 'ry'
    elif matrix[6][1] == 'rb': matrix[6][1] = 'bo'
    elif matrix[6][1] == 'bo': matrix[6][1] = 'og'
    elif matrix[6][1] == 'og': matrix[6][1] = 'gr'
    elif matrix[6][1] == 'gr': matrix[6][1] = 'rb'
    elif matrix[6][1] == 'bw': matrix[6][1] = 'wg'
    elif matrix[6][1] == 'wg': matrix[6][1] = 'gy'
    elif matrix[6][1] == 'gy': matrix[6][1] = 'yb'
    elif matrix[6][1] == 'yb': matrix[6][1] = 'bw'
    elif matrix[6][1] == 'by': matrix[6][1] = 'yg'
    elif matrix[6][1] == 'yg': matrix[6][1] = 'gw'
    elif matrix[6][1] == 'gw': matrix[6][1] = 'wb'
    elif matrix[6][1] == 'wb': matrix[6][1] = 'by'

    if matrix[0][1] == 'rw': matrix[0][1] = 'wo'
    elif matrix[0][1] == 'wo': matrix[0][1] = 'oy'
    elif matrix[0][1] == 'oy': matrix[0][1] = 'yr'
    elif matrix[0][1] == 'yr': matrix[0][1] = 'rw'
    elif matrix[0][1] == 'rg': matrix[0][1] = 'go' 
    elif matrix[0][1] == 'go': matrix[0][1] = 'ob'
    elif matrix[0][1] == 'ob': matrix[0][1] = 'br' 
    elif matrix[0][1] == 'br': matrix[0][1] = 'rg' 
    elif matrix[0][1] == 'ry': matrix[0][1] = 'yo'
    elif matrix[0][1] == 'yo': matrix[0][1] = 'ow'
    elif matrix[0][1] == 'ow': matrix[0][1] = 'wr'
    elif matrix[0][1] == 'wr': matrix[0][1] = 'ry'
    elif matrix[0][1] == 'rb': matrix[0][1] = 'bo'
    elif matrix[0][1] == 'bo': matrix[0][1] = 'og'
    elif matrix[0][1] == 'og': matrix[0][1] = 'gr'
    elif matrix[0][1] == 'gr': matrix[0][1] = 'rb'
    elif matrix[0][1] == 'bw': matrix[0][1] = 'wg'
    elif matrix[0][1] == 'wg': matrix[0][1] = 'gy'
    elif matrix[0][1] == 'gy': matrix[0][1] = 'yb'
    elif matrix[0][1] == 'yb': matrix[0][1] = 'bw'
    elif matrix[0][1] == 'by': matrix[0][1] = 'yg'
    elif matrix[0][1] == 'yg': matrix[0][1] = 'gw'
    elif matrix[0][1] == 'gw': matrix[0][1] = 'wb'
    elif matrix[0][1] == 'wb': matrix[0][1] = 'by'

    if matrix[9][1] == 'rw': matrix[9][1] = 'wo'
    elif matrix[9][1] == 'wo': matrix[9][1] = 'oy'
    elif matrix[9][1] == 'oy': matrix[9][1] = 'yr'
    elif matrix[9][1] == 'yr': matrix[9][1] = 'rw'
    elif matrix[9][1] == 'rg': matrix[9][1] = 'go'
    elif matrix[9][1] == 'go': matrix[9][1] = 'ob'
    elif matrix[9][1] == 'ob': matrix[9][1] = 'br'
    elif matrix[9][1] == 'br': matrix[9][1] = 'rg'
    elif matrix[9][1] == 'ry': matrix[9][1] = 'yo'
    elif matrix[9][1] == 'yo': matrix[9][1] = 'ow'
    elif matrix[9][1] == 'ow': matrix[9][1] = 'wr'
    elif matrix[9][1] == 'wr': matrix[9][1] = 'ry'
    elif matrix[9][1] == 'rb': matrix[9][1] = 'bo'
    elif matrix[9][1] == 'bo': matrix[9][1] = 'og'
    elif matrix[9][1] == 'og': matrix[9][1] = 'gr'
    elif matrix[9][1] == 'gr': matrix[9][1] = 'rb'
    elif matrix[9][1] == 'bw': matrix[9][1] = 'wg'
    elif matrix[9][1] == 'wg': matrix[9][1] = 'gy'
    elif matrix[9][1] == 'gy': matrix[9][1] = 'yb'
    elif matrix[9][1] == 'yb': matrix[9][1] = 'bw'
    elif matrix[9][1] == 'by': matrix[9][1] = 'yg'
    elif matrix[9][1] == 'yg': matrix[9][1] = 'gw'
    elif matrix[9][1] == 'gw': matrix[9][1] = 'wb'
    elif matrix[9][1] == 'wb': matrix[9][1] = 'by'

    if matrix[21][1] == 'rw': matrix[21][1] = 'wo'
    elif matrix[21][1] == 'wo': matrix[21][1] = 'oy'
    elif matrix[21][1] == 'oy': matrix[21][1] = 'yr'
    elif matrix[21][1] == 'yr': matrix[21][1] = 'rw'
    elif matrix[21][1] == 'rg': matrix[21][1] = 'go'
    elif matrix[21][1] == 'go': matrix[21][1] = 'ob'
    elif matrix[21][1] == 'ob': matrix[21][1] = 'br'
    elif matrix[21][1] == 'br': matrix[21][1] = 'rg'
    elif matrix[21][1] == 'ry': matrix[21][1] = 'yo'
    elif matrix[21][1] == 'yo': matrix[21][1] = 'ow'
    elif matrix[21][1] == 'ow': matrix[21][1] = 'wr'
    elif matrix[21][1] == 'wr': matrix[21][1] = 'ry'
    elif matrix[21][1] == 'rb': matrix[21][1] = 'bo'
    elif matrix[21][1] == 'bo': matrix[21][1] = 'og'
    elif matrix[21][1] == 'og': matrix[21][1] = 'gr'
    elif matrix[21][1] == 'gr': matrix[21][1] = 'rb'
    elif matrix[21][1] == 'bw': matrix[21][1] = 'wg'
    elif matrix[21][1] == 'wg': matrix[21][1] = 'gy'
    elif matrix[21][1] == 'gy': matrix[21][1] = 'yb'
    elif matrix[21][1] == 'yb': matrix[21][1] = 'bw'
    elif matrix[21][1] == 'by': matrix[21][1] = 'yg'
    elif matrix[21][1] == 'yg': matrix[21][1] = 'gw'
    elif matrix[21][1] == 'gw': matrix[21][1] = 'wb'
    elif matrix[21][1] == 'wb': matrix[21][1] = 'by'

    if matrix[15][1] == 'rw': matrix[15][1] = 'wo'
    elif matrix[15][1] == 'wo': matrix[15][1] = 'oy'
    elif matrix[15][1] == 'oy': matrix[15][1] = 'yr'
    elif matrix[15][1] == 'yr': matrix[15][1] = 'rw'
    elif matrix[15][1] == 'rg': matrix[15][1] = 'go'
    elif matrix[15][1] == 'go': matrix[15][1] = 'ob'
    elif matrix[15][1] == 'ob': matrix[15][1] = 'br'
    elif matrix[15][1] == 'br': matrix[15][1] = 'rg'
    elif matrix[15][1] == 'ry': matrix[15][1] = 'yo'
    elif matrix[15][1] == 'yo': matrix[15][1] = 'ow'
    elif matrix[15][1] == 'ow': matrix[15][1] = 'wr'
    elif matrix[15][1] == 'wr': matrix[15][1] = 'ry'
    elif matrix[15][1] == 'rb': matrix[15][1] = 'bo'
    elif matrix[15][1] == 'bo': matrix[15][1] = 'og'
    elif matrix[15][1] == 'og': matrix[15][1] = 'gr'
    elif matrix[15][1] == 'gr': matrix[15][1] = 'rb'
    elif matrix[15][1] == 'bw': matrix[15][1] = 'wg'
    elif matrix[15][1] == 'wg': matrix[15][1] = 'gy'
    elif matrix[15][1] == 'gy': matrix[15][1] = 'yb'
    elif matrix[15][1] == 'yb': matrix[15][1] = 'bw'
    elif matrix[15][1] == 'by': matrix[15][1] = 'yg'
    elif matrix[15][1] == 'yg': matrix[15][1] = 'gw'
    elif matrix[15][1] == 'gw': matrix[15][1] = 'wb'
    elif matrix[15][1] == 'wb': matrix[15][1] = 'by'

    if matrix[3][1] == 'rw': matrix[3][1] = 'wo'
    elif matrix[3][1] == 'wo': matrix[3][1] = 'oy'
    elif matrix[3][1] == 'oy': matrix[3][1] = 'yr'
    elif matrix[3][1] == 'yr': matrix[3][1] = 'rw'
    elif matrix[3][1] == 'rg': matrix[3][1] = 'go'
    elif matrix[3][1] == 'go': matrix[3][1] = 'ob'
    elif matrix[3][1] == 'ob': matrix[3][1] = 'br'
    elif matrix[3][1] == 'br': matrix[3][1] = 'rg'
    elif matrix[3][1] == 'ry': matrix[3][1] = 'yo'
    elif matrix[3][1] == 'yo': matrix[3][1] = 'ow'
    elif matrix[3][1] == 'ow': matrix[3][1] = 'wr'
    elif matrix[3][1] == 'wr': matrix[3][1] = 'ry'
    elif matrix[3][1] == 'rb': matrix[3][1] = 'bo'
    elif matrix[3][1] == 'bo': matrix[3][1] = 'og'
    elif matrix[3][1] == 'og': matrix[3][1] = 'gr'
    elif matrix[3][1] == 'gr': matrix[3][1] = 'rb'
    elif matrix[3][1] == 'bw': matrix[3][1] = 'wg'
    elif matrix[3][1] == 'wg': matrix[3][1] = 'gy'
    elif matrix[3][1] == 'gy': matrix[3][1] = 'yb'
    elif matrix[3][1] == 'yb': matrix[3][1] = 'bw'
    elif matrix[3][1] == 'by': matrix[3][1] = 'yg'
    elif matrix[3][1] == 'yg': matrix[3][1] = 'gw'
    elif matrix[3][1] == 'gw': matrix[3][1] = 'wb'
    elif matrix[5][1] == 'wb': matrix[3][1] = 'by'

    matrix[18][1], matrix[24][1], matrix[6][1], matrix[0][1] = matrix[0][1], matrix[18][1], matrix[24][1], matrix[6][1]
    matrix[9][1], matrix[21][1], matrix[15][1], matrix[3][1] = matrix[3][1], matrix[9][1], matrix[21][1], matrix[15][1]
  if args[0] == 'y':
    if matrix[18][1] == 'rw': matrix[18][1] = 'bw'
    elif matrix[18][1] == 'bw': matrix[18][1] = 'ow'
    elif matrix[18][1] == 'ow': matrix[18][1] = 'gw'
    elif matrix[18][1] == 'gw': matrix[18][1] = 'rw'
    elif matrix[18][1] == 'rb': matrix[18][1] = 'yb'
    elif matrix[18][1] == 'yb': matrix[18][1] = 'ob'
    elif matrix[18][1] == 'ob': matrix[18][1] = 'wb'
    elif matrix[18][1] == 'wb': matrix[18][1] = 'rb'
    elif matrix[18][1] == 'ry': matrix[18][1] = 'gy'
    elif matrix[18][1] == 'gy': matrix[18][1] = 'oy'
    elif matrix[18][1] == 'oy': matrix[18][1] = 'by'
    elif matrix[18][1] == 'by': matrix[18][1] = 'ry'
    elif matrix[18][1] == 'rg': matrix[18][1] = 'wg'
    elif matrix[18][1] == 'wg': matrix[18][1] = 'og'
    elif matrix[18][1] == 'og': matrix[18][1] = 'yg'
    elif matrix[18][1] == 'yg': matrix[18][1] = 'rg'
    elif matrix[18][1] == 'wr': matrix[18][1] = 'gr'
    elif matrix[18][1] == 'gr': matrix[18][1] = 'yr'
    elif matrix[18][1] == 'yr': matrix[18][1] = 'br'
    elif matrix[18][1] == 'br': matrix[18][1] = 'wr'
    elif matrix[18][1] == 'wo': matrix[18][1] = 'bo'
    elif matrix[18][1] == 'bo': matrix[18][1] = 'yo'
    elif matrix[18][1] == 'yo': matrix[18][1] = 'go'
    elif matrix[18][1] == 'go': matrix[18][1] = 'wo'

    if matrix[24][1] == 'rw': matrix[24][1] = 'bw'
    elif matrix[24][1] == 'bw': matrix[24][1] = 'ow' 
    elif matrix[24][1] == 'ow': matrix[24][1] = 'gw'
    elif matrix[24][1] == 'gw': matrix[24][1] = 'rw'
    elif matrix[24][1] == 'rb': matrix[24][1] = 'yb'
    elif matrix[24][1] == 'yb': matrix[24][1] = 'ob'
    elif matrix[24][1] == 'ob': matrix[24][1] = 'wb'
    elif matrix[24][1] == 'wb': matrix[24][1] = 'rb'
    elif matrix[24][1] == 'ry': matrix[24][1] = 'gy'
    elif matrix[24][1] == 'gy': matrix[24][1] = 'oy'
    elif matrix[24][1] == 'oy': matrix[24][1] = 'by'
    elif matrix[24][1] == 'by': matrix[24][1] = 'ry'
    elif matrix[24][1] == 'rg': matrix[24][1] = 'wg'
    elif matrix[24][1] == 'wg': matrix[24][1] = 'og'
    elif matrix[24][1] == 'og': matrix[24][1] = 'yg'
    elif matrix[24][1] == 'yg': matrix[24][1] = 'rg'
    elif matrix[24][1] == 'wr': matrix[24][1] = 'gr'
    elif matrix[24][1] == 'gr': matrix[24][1] = 'yr'
    elif matrix[24][1] == 'yr': matrix[24][1] = 'br'
    elif matrix[24][1] == 'br': matrix[24][1] = 'wr'
    elif matrix[24][1] == 'wo': matrix[24][1] = 'bo'
    elif matrix[24][1] == 'bo': matrix[24][1] = 'yo'
    elif matrix[24][1] == 'yo': matrix[24][1] = 'go'
    elif matrix[24][1] == 'go': matrix[24][1] = 'wo'

    if matrix[26][1] == 'rw': matrix[26][1] = 'bw'
    elif matrix[26][1] == 'bw': matrix[26][1] = 'ow' 
    elif matrix[26][1] == 'ow': matrix[26][1] = 'gw'
    elif matrix[26][1] == 'gw': matrix[26][1] = 'rw'
    elif matrix[26][1] == 'rb': matrix[26][1] = 'yb'
    elif matrix[26][1] == 'yb': matrix[26][1] = 'ob'
    elif matrix[26][1] == 'ob': matrix[26][1] = 'wb'
    elif matrix[26][1] == 'wb': matrix[26][1] = 'rb'
    elif matrix[26][1] == 'ry': matrix[26][1] = 'gy'
    elif matrix[26][1] == 'gy': matrix[26][1] = 'oy'
    elif matrix[26][1] == 'oy': matrix[26][1] = 'by'
    elif matrix[26][1] == 'by': matrix[26][1] = 'ry'
    elif matrix[26][1] == 'rg': matrix[26][1] = 'wg'
    elif matrix[26][1] == 'wg': matrix[26][1] = 'og'
    elif matrix[26][1] == 'og': matrix[26][1] = 'yg'
    elif matrix[26][1] == 'yg': matrix[26][1] = 'rg'
    elif matrix[26][1] == 'wr': matrix[26][1] = 'gr'
    elif matrix[26][1] == 'gr': matrix[26][1] = 'yr'
    elif matrix[26][1] == 'yr': matrix[26][1] = 'br'
    elif matrix[26][1] == 'br': matrix[26][1] = 'wr'
    elif matrix[26][1] == 'wo': matrix[26][1] = 'bo'
    elif matrix[26][1] == 'bo': matrix[26][1] = 'yo'
    elif matrix[26][1] == 'yo': matrix[26][1] = 'go'
    elif matrix[26][1] == 'go': matrix[26][1] = 'wo'

    if matrix[20][1] == 'rw': matrix[20][1] = 'bw'
    elif matrix[20][1] == 'bw': matrix[20][1] = 'ow'
    elif matrix[20][1] == 'ow': matrix[20][1] = 'gw'
    elif matrix[20][1] == 'gw': matrix[20][1] = 'rw'
    elif matrix[20][1] == 'rb': matrix[20][1] = 'yb'
    elif matrix[20][1] == 'yb': matrix[20][1] = 'ob'
    elif matrix[20][1] == 'ob': matrix[20][1] = 'wb'
    elif matrix[20][1] == 'wb': matrix[20][1] = 'rb'
    elif matrix[20][1] == 'ry': matrix[20][1] = 'gy'
    elif matrix[20][1] == 'gy': matrix[20][1] = 'oy'
    elif matrix[20][1] == 'oy': matrix[20][1] = 'by'
    elif matrix[20][1] == 'by': matrix[20][1] = 'ry'
    elif matrix[20][1] == 'rg': matrix[20][1] = 'wg'
    elif matrix[20][1] == 'wg': matrix[20][1] = 'og'
    elif matrix[20][1] == 'og': matrix[20][1] = 'yg'
    elif matrix[20][1] == 'yg': matrix[20][1] = 'rg'
    elif matrix[20][1] == 'wr': matrix[20][1] = 'gr'
    elif matrix[20][1] == 'gr': matrix[20][1] = 'yr'
    elif matrix[20][1] == 'yr': matrix[20][1] = 'br'
    elif matrix[20][1] == 'br': matrix[20][1] = 'wr'
    elif matrix[20][1] == 'wo': matrix[20][1] = 'bo'
    elif matrix[20][1] == 'bo': matrix[20][1] = 'yo'
    elif matrix[20][1] == 'yo': matrix[20][1] = 'go'
    elif matrix[20][1] == 'go': matrix[20][1] = 'wo'

    if matrix[21][1] == 'rw': matrix[21][1] = 'bw'
    elif matrix[21][1] == 'bw': matrix[21][1] = 'ow' 
    elif matrix[21][1] == 'ow': matrix[21][1] = 'gw'
    elif matrix[21][1] == 'gw': matrix[21][1] = 'rw'
    elif matrix[21][1] == 'rb': matrix[21][1] = 'yb'
    elif matrix[21][1] == 'yb': matrix[21][1] = 'ob'
    elif matrix[21][1] == 'ob': matrix[21][1] = 'wb'
    elif matrix[21][1] == 'wb': matrix[21][1] = 'rb'
    elif matrix[21][1] == 'ry': matrix[21][1] = 'gy'
    elif matrix[21][1] == 'gy': matrix[21][1] = 'oy'
    elif matrix[21][1] == 'oy': matrix[21][1] = 'by'
    elif matrix[21][1] == 'by': matrix[21][1] = 'ry'
    elif matrix[21][1] == 'rg': matrix[21][1] = 'wg'
    elif matrix[21][1] == 'wg': matrix[21][1] = 'og'
    elif matrix[21][1] == 'og': matrix[21][1] = 'yg'
    elif matrix[21][1] == 'yg': matrix[21][1] = 'rg'
    elif matrix[21][1] == 'wr': matrix[21][1] = 'gr'
    elif matrix[21][1] == 'gr': matrix[21][1] = 'yr'
    elif matrix[21][1] == 'yr': matrix[21][1] = 'br'
    elif matrix[21][1] == 'br': matrix[21][1] = 'wr'
    elif matrix[21][1] == 'wo': matrix[21][1] = 'bo'
    elif matrix[21][1] == 'bo': matrix[21][1] = 'yo'
    elif matrix[21][1] == 'yo': matrix[21][1] = 'go'
    elif matrix[21][1] == 'go': matrix[21][1] = 'wo'

    if matrix[25][1] == 'rw': matrix[25][1] = 'bw'
    elif matrix[25][1] == 'bw': matrix[25][1] = 'ow'
    elif matrix[25][1] == 'ow': matrix[25][1] = 'gw'
    elif matrix[25][1] == 'gw': matrix[25][1] = 'rw'
    elif matrix[25][1] == 'rb': matrix[25][1] = 'yb'
    elif matrix[25][1] == 'yb': matrix[25][1] = 'ob'
    elif matrix[25][1] == 'ob': matrix[25][1] = 'wb'
    elif matrix[25][1] == 'wb': matrix[25][1] = 'rb'
    elif matrix[25][1] == 'ry': matrix[25][1] = 'gy'
    elif matrix[25][1] == 'gy': matrix[25][1] = 'oy'
    elif matrix[25][1] == 'oy': matrix[25][1] = 'by'
    elif matrix[25][1] == 'by': matrix[25][1] = 'ry'
    elif matrix[25][1] == 'rg': matrix[25][1] = 'wg'
    elif matrix[25][1] == 'wg': matrix[25][1] = 'og'
    elif matrix[25][1] == 'og': matrix[25][1] = 'yg'
    elif matrix[25][1] == 'yg': matrix[25][1] = 'rg'
    elif matrix[25][1] == 'wr': matrix[25][1] = 'gr'
    elif matrix[25][1] == 'gr': matrix[25][1] = 'yr'
    elif matrix[25][1] == 'yr': matrix[25][1] = 'br'
    elif matrix[25][1] == 'br': matrix[25][1] = 'wr'
    elif matrix[25][1] == 'wo': matrix[25][1] = 'bo'
    elif matrix[25][1] == 'bo': matrix[25][1] = 'yo'
    elif matrix[25][1] == 'yo': matrix[25][1] = 'go'
    elif matrix[25][1] == 'go': matrix[25][1] = 'wo'

    if matrix[23][1] == 'rw': matrix[23][1] = 'bw'
    elif matrix[23][1] == 'bw': matrix[23][1] = 'ow'
    elif matrix[23][1] == 'ow': matrix[23][1] = 'gw'
    elif matrix[23][1] == 'gw': matrix[23][1] = 'rw'
    elif matrix[23][1] == 'rb': matrix[23][1] = 'yb'
    elif matrix[23][1] == 'yb': matrix[23][1] = 'ob'
    elif matrix[23][1] == 'ob': matrix[23][1] = 'wb'
    elif matrix[23][1] == 'wb': matrix[23][1] = 'rb'
    elif matrix[23][1] == 'ry': matrix[23][1] = 'gy'
    elif matrix[23][1] == 'gy': matrix[23][1] = 'oy'
    elif matrix[23][1] == 'oy': matrix[23][1] = 'by'
    elif matrix[23][1] == 'by': matrix[23][1] = 'ry'
    elif matrix[23][1] == 'rg': matrix[23][1] = 'wg'
    elif matrix[23][1] == 'wg': matrix[23][1] = 'og'
    elif matrix[23][1] == 'og': matrix[23][1] = 'yg'
    elif matrix[23][1] == 'yg': matrix[23][1] = 'rg'
    elif matrix[23][1] == 'wr': matrix[23][1] = 'gr'
    elif matrix[23][1] == 'gr': matrix[23][1] = 'yr'
    elif matrix[23][1] == 'yr': matrix[23][1] = 'br'
    elif matrix[23][1] == 'br': matrix[23][1] = 'wr'
    elif matrix[23][1] == 'wo': matrix[23][1] = 'bo'
    elif matrix[23][1] == 'bo': matrix[23][1] = 'yo'
    elif matrix[23][1] == 'yo': matrix[23][1] = 'go'
    elif matrix[23][1] == 'go': matrix[23][1] = 'wo'

    if matrix[19][1] == 'rw': matrix[19][1] = 'bw'
    elif matrix[19][1] == 'bw': matrix[19][1] = 'ow'
    elif matrix[19][1] == 'ow': matrix[19][1] = 'gw'
    elif matrix[19][1] == 'gw': matrix[19][1] = 'rw'
    elif matrix[19][1] == 'rb': matrix[19][1] = 'yb'
    elif matrix[19][1] == 'yb': matrix[19][1] = 'ob'
    elif matrix[19][1] == 'ob': matrix[19][1] = 'wb'
    elif matrix[19][1] == 'wb': matrix[19][1] = 'rb'
    elif matrix[19][1] == 'ry': matrix[19][1] = 'gy'
    elif matrix[19][1] == 'gy': matrix[19][1] = 'oy'
    elif matrix[19][1] == 'oy': matrix[19][1] = 'by'
    elif matrix[19][1] == 'by': matrix[19][1] = 'ry'
    elif matrix[19][1] == 'rg': matrix[19][1] = 'wg'
    elif matrix[19][1] == 'wg': matrix[19][1] = 'og'
    elif matrix[19][1] == 'og': matrix[19][1] = 'yg'
    elif matrix[19][1] == 'yg': matrix[19][1] = 'rg'
    elif matrix[19][1] == 'wr': matrix[19][1] = 'gr'
    elif matrix[19][1] == 'gr': matrix[19][1] = 'yr'
    elif matrix[19][1] == 'yr': matrix[19][1] = 'br'
    elif matrix[19][1] == 'br': matrix[19][1] = 'wr'
    elif matrix[19][1] == 'wo': matrix[19][1] = 'bo'
    elif matrix[19][1] == 'bo': matrix[19][1] = 'yo'
    elif matrix[19][1] == 'yo': matrix[19][1] = 'go'
    elif matrix[19][1] == 'go': matrix[19][1] = 'wo'

    matrix[18][1], matrix[24][1], matrix[26][1], matrix[20][1] = matrix[20][1], matrix[18][1], matrix[24][1], matrix[26][1]
    matrix[21][1], matrix[25][1], matrix[23][1], matrix[19][1] = matrix[19][1], matrix[21][1], matrix[25][1], matrix[23][1]


def draw():
    glClear(GL_COLOR_BUFFER_BIT|GL_DEPTH_BUFFER_BIT)
    #glRotatef(2,1,3,0)
    rc()
    glutSwapBuffers()

def timer(i):
    glutPostRedisplay()
    glutTimerFunc(50,timer,1)


# PROGRAMA PRINCIPAL
glutInit(sys.argv)
glutInitDisplayMode(GLUT_DOUBLE | GLUT_RGBA | GLUT_DEPTH | GLUT_MULTISAMPLE)
glutInitWindowSize(800,600)
glutCreateWindow("rubik's cube")
glutDisplayFunc(draw)
glEnable(GL_MULTISAMPLE)
glEnable(GL_DEPTH_TEST)
glClearColor(0.,0.,0.,1.)
gluPerspective(45,800.0/600.0,0.1,50.0)
glTranslatef(0.0,0.0,-10)
glRotatef(45,1,1,1)
glutTimerFunc(50,timer,1)
glutKeyboardFunc(keyPressed)
glutMainLoop()